# Generated by Django 4.2.7 on 2023-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=256)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
